// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBur92yoyafPSI9b-PDR2dqm_I7dxWxeSk',
    appId: '1:450190786438:web:309414185d481d74b47607',
    messagingSenderId: '450190786438',
    projectId: 'transgo-6dd13',
    authDomain: 'transgo-6dd13.firebaseapp.com',
    storageBucket: 'transgo-6dd13.firebasestorage.app',
    measurementId: 'G-WMK9ZG6DEP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNC53YLLSxD2CpDrtBRpCUwJiLRuA7A60',
    appId: '1:450190786438:android:75ab72dff3a3efdab47607',
    messagingSenderId: '450190786438',
    projectId: 'transgo-6dd13',
    storageBucket: 'transgo-6dd13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlnIITo5Pa8wyc72Q_oQlTS8unBy8Pk1g',
    appId: '1:450190786438:ios:7aac1db43d6e6f14b47607',
    messagingSenderId: '450190786438',
    projectId: 'transgo-6dd13',
    storageBucket: 'transgo-6dd13.firebasestorage.app',
    iosBundleId: 'com.example.transgoPassenger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlnIITo5Pa8wyc72Q_oQlTS8unBy8Pk1g',
    appId: '1:450190786438:ios:7aac1db43d6e6f14b47607',
    messagingSenderId: '450190786438',
    projectId: 'transgo-6dd13',
    storageBucket: 'transgo-6dd13.firebasestorage.app',
    iosBundleId: 'com.example.transgoPassenger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBur92yoyafPSI9b-PDR2dqm_I7dxWxeSk',
    appId: '1:450190786438:web:f389727fdff8ef11b47607',
    messagingSenderId: '450190786438',
    projectId: 'transgo-6dd13',
    authDomain: 'transgo-6dd13.firebaseapp.com',
    storageBucket: 'transgo-6dd13.firebasestorage.app',
    measurementId: 'G-F5S6ZCHXND',
  );
}
